### PR TITLE
Enhance Device with DevicePlatform resolving

### LINKED ISSUE #24: Detection systems provide
Whether DeviceUtils can provide a way to check the phone system, the system returns an enumeration
ios, mac ox, android, etc., or else we'll get from the inside UserAgent
thank you

### PR DESCRIPTION
**Pull request by okohub**
fixes #24

### CODE REVIEW

**Comment by royclarkson** [comment]
Thanks! Have you signed the [CLA](https://github.com/spring-projects/spring-mobile/blob/master/CONTRIBUTING.md)?

**Comment by okohub** [comment]
@royclarkson Ah yes, here is my confirmation number 118920150428025713

**Comment by royclarkson** [comment]
Great, thanks. Can you clarify the goal of this addition? Is it basically to add the platform property to the device object? It'd help to update the docs too, if you don't mind.

**Comment by okohub** [comment]
@royclarkson no problem,

Yes it is as you said, a very simple approach to access device platform. We have lots of spring based projects and sometimes accessing device platform is critical. Instead of writing a new resolver for device platform, with using User-Agent header again, spring mobile can do that for us.

Here i wrote down only 2 platforms which are most commonly used. Various platforms can be added of course, for example BB and Windows Phone. 

I am also thinking about refactoring resolve method in the future, it is quite hard to read i think.

**Comment by royclarkson** [comment]
You may have noticed this project isn't receiving much attention these days. Obviously, the industry is favoring responsive design over server side user agent detection. However, it can still be useful in situations. You are correct about the resolve method. It's become unmanageable. I had some ideas for refactoring the resolve method for a 1.2.0 release. Making it modular, where you register several "DeviceResolverStrategy" instances with the DeviceResolver would be really nice. Something like the MessageConverter model used in Spring MVC. If you want to work on that, I'd be happy to facilitate getting the changes into a release.

**Comment by royclarkson** [comment]
Thanks!

**Comment by royclarkson** [comment]
@okohub let me know if you have anything else to include, otherwise I can push out a 1.1.4 release with these changes. Any kind of major changes would probably need to go in a 1.2.0 milestone.

**Comment by okohub** [comment]
@royclarkson thanks, I will try to contribute to 1.2.0 release.

**Comment by okohub** [comment]
Hi @royclarkson,
When will you push a new release?

**Comment by royclarkson** [comment]
@okohub I can push it out as soon as I update the docs. Would you mind sharing how you are using this project and if you are using other Spring projects? Feel free to email me privately at rclarkson at pivotal dot io, if you like.

**Comment by royclarkson** [comment]
@okohub 1.1.4.RELEASE is published with this change. thanks again.

**Pull request merged**
